objects:
  - name: camera
    object_type: record
    subindexes:
      - name: num_of_capture
        data_type: uint8
        description: number of images to capture or 0 for endless
        default: 1

      - name: delay
        data_type: uint32
        description: delay between captures in milliseconds

      - name: integration_time
        data_type: uint32
        description: camera integration time in milliseconds

      - name: status
        data_type: uint8
        description: the camera status

      - name: last_capture
        data_type: domain
        description: the last raw capture
        access_type: ro

      - name: last_display_image
        data_type: domain
        description: the last capture convert to nice display image
        access_type: ro

      - name: last_capture_time
        data_type: uint64
        description: the last capture timestamp
        access_type: ro

      - name: save_captures
        data_type: bool
        description: flag to save captured images
        access_type: rw
        default: true

      - name: temperature
        data_type: int8
        description: the camera temperature in celsius
        access_type: ro

  - name: tec
    object_type: record
    subindexes:
      - name: status
        data_type: bool
        description: the tec controller status

      - name: saturated
        data_type: bool
        description: the tec is saturated
        access_type: ro

      - name: pid_setpoint
        data_type: int8
        description: the tec target temperature in celsius

      - name: pid_kp
        data_type: float32
        description: the PID proportional constant
        access_type: const
        value: 0.5

      - name: pid_ki
        data_type: float32
        description: the PID intergral constant
        access_type: const
        value: 0.0

      - name: pid_kd
        data_type: float32
        description: the PID derivative constant
        access_type: const
        value: 0.1

      - name: pid_delay
        data_type: uint32
        description: the delay between PID loops in milliseconds
        access_type: rw
        value: 250

      - name: moving_avg_samples
        data_type: uint8
        description: the number of reading used to calcuate the moving average to determine if saturated
        access_type: rw
        value: 4

      - name: saturation_diff
        data_type: uint8
        description: the difference between the lowest and current temperature (in celsius) to flag as saturated
        access_type: rw
        value: 3

      - name: cooldown_temperature
        data_type: int8
        description: once saturated the TEC controller cannot be enable until the camera temperature (in celsius) is greater this value
        access_type: rw
        value: 40

tpdos:
  - num: 3
    fields:
      - [camera, status]
      - [camera, temperature]
      - [tec, status]
      - [tec, saturated]
    delay_ms: 1000
